Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
  	vb.memory = 2048
  end

  # Create Centos VM
  config.vm.define "centos" do |centos|
    # Set VirtualBox image
    centos.vm.box = "centos/7"

    # Sync folders between local and virtual machine
    centos.vm.synced_folder "sync/", "/vagrant"

    # Set-up port forwarding
    centos.vm.network "forwarded_port", guest: 80, host: 8888

    # Provisioning script to run
    centos.vm.provision "shell", path: "install.sh"
  end

  # Create Ubuntu VM
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
  end
end
