Vagrant.configure("2") do |config|

    # Set VirtualBox image
    config.vm.box = "centos/7"
  
    # Sync folders between local and virtual machine
    config.vm.synced_folder "sync/", "/vagrant"
  
    # Provisioning script to run
    config.vm.provision "shell", path: "task.sh"
  end
  