Vagrant.configure("2") do |config|

  # Set VirtualBox image
  config.vm.box = "centos/7"

  # Sync folders between local and virtual machine
  config.vm.synced_folder "sync/", "/vagrant"

  # Set-up port forwarding for HTTP and HTTPS
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.network "forwarded_port", guest: 443, host: 8443

  # Provisioning script to run
  config.vm.provision "shell", path: "install.sh"
end
